services:
  bahmni-proxy:
    build: bahmni-proxy/
    networks:
      bahmni:
    ports:
      - "80:80"
    deploy:
      mode: global

  bahmniapps:
    build: bahmniapps/
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:8900/bahmniapps/home/index.html"
      timeout: 20s
    networks:
      bahmni:
    deploy:
      mode: global

  bahmni-config:
    build: bahmni_config/
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:8901/bahmni_config/openmrs/apps/home/app.json"
      timeout: 20s
    networks:
      bahmni:
    volumes:
      - "${BAHMNI_CONFIG_PATH}:/var/www/bahmni_config"
    deploy:
      mode: global

  openmrs-tomcat:
    depends_on:
      - openmrs-mysql
    environment:
      DB_AUTO_UPDATE: "true"
      DB_CREATE_TABLES: "true"
      DB_DATABASE: "${MYSQL_DB:-openmrs}"
      DB_HOST: openmrs-mysql
      DB_PASSWORD: "${MYSQL_PASSWORD:-Admin123}"
      DB_USERNAME: "${MYSQL_USER:-openmrs}"
      MODULE_WEB_ADMIN: "true"
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:8080/openmrs/"
      timeout: 20s
    image: "openmrs/openmrs-distro-platform:2.1.3"
    networks:
      bahmni:
    volumes:
      - "openmrs-tomcat-data:/usr/local/tomcat/.OpenMRS/"
      - /usr/local/tomcat/.OpenMRS/owa/
      - "${OPENMRS_MODULES_PATH}:/usr/local/tomcat/.OpenMRS/modules/"
      - "${OPENMRS_CONFIG_PATH}:/usr/local/tomcat/.OpenMRS/configuration/"
    deploy:
      mode: global

  openmrs-mysql:
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: "${MYSQL_DB:-openmrs}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-Admin123}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-Admin123}"
      MYSQL_USER: "${MYSQL_USER:-openmrs}"
    healthcheck:
      test: "exit 0"
    image: "mysql:5.6"
    networks:
      bahmni:
    volumes:
      - "openmrs-mysql-data:/var/lib/mysql"
    deploy:
      mode: global

version: "3.7"
volumes:
  openmrs-mysql-data:
    external: true
  openmrs-tomcat-data:
networks:
  bahmni:
