services:
  bahmni-proxy:
    image: "bahmni-proxy"
    networks:
      bahmni:
        aliases:
          - bahmni-proxy
    ports:
      - "80:80"
    volumes:
      - "./bahmni-proxy/confs:/usr/local/apache2/conf/extra"

  OpenMRS-tomcat:
    depends_on:
      - OpenMRS-mysql
    environment:
      DB_AUTO_UPDATE: "true"
      DB_CREATE_TABLES: "true"
      DB_DATABASE: "${MYSQL_DB:-openmrs}"
      DB_HOST: OpenMRS-mysql
      DB_PASSWORD: "${MYSQL_PASSWORD:-Admin123}"
      DB_USERNAME: "${MYSQL_USER:-openmrs}"
      MODULE_WEB_ADMIN: "true"
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:8080/openmrs/"
      timeout: 20s
    image: "openmrs/openmrs-distro-platform:2.1.3"
    networks:
      bahmni:
        aliases:
          - openmrs-1
    volumes:
      - "OpenMRS-tomcat-data:/usr/local/tomcat/.OpenMRS/"
      - "/home/fabienc/repos/bahmni-distro-hsc/target/bahmni-distro-hsc-1.0.0-SNAPSHOT/openmrs_modules:/usr/local/tomcat/.OpenMRS/modules/"
      - /usr/local/tomcat/.OpenMRS/owa/

  bahmniapps:
    image: "bahmniapps:latest"
    networks:
      bahmni:
        aliases:
          - bahmniapps-1
    ports:
      - "8900:8900"
    volumes:
      - "./bahmniapps/confs:/usr/local/apache2/conf/extra"

  OpenMRS-mysql:
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: "${MYSQL_DB:-openmrs}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-Admin123}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-Admin123}"
      MYSQL_USER: "${MYSQL_USER:-openmrs}"
    healthcheck:
      test: "exit 0"
    image: "mysql:5.6"
    networks:
      bahmni:
        aliases:
          - openmrs-db
    volumes:
      - "OpenMRS-mysql-data:/var/lib/mysql"
version: "2.1"
volumes:
  OpenMRS-tomcat-data: ~
  OpenMRS-mysql-data: ~
networks:
  bahmni:
